#ENC[AES256_GCM,data:WYv9RL+cSFaP8FZ/0idW5/0AHBld,iv:qvTjSG8GE1iIAOKOprXFBms/qQH7Si3X0Qi/gslhtvM=,tag:JfFCcIrAyeDoutqShw0eJQ==,type:comment]
#ENC[AES256_GCM,data:1GY4KLSAJBtC+ljKbB2KCrQ0m9jgB/DLtTmAyvaJU3Djz2Hc0hasBR9yuDdJMpE=,iv:kCkqqTAjiF2eveqiKV+a1SpClbBHky1XNnL4NfvA0dc=,tag:jWYoO8Vop3zCC9Ei75vVZg==,type:comment]
placeholder: ENC[AES256_GCM,data:liAR5h9ZGQw38A==,iv:QUJmTzII3o2QNJmyQ3csb5Zb/CtW8DsIaJ4gmBnfYjI=,tag:tK2RGeWuGt5ffG3bixG3wA==,type:str]
nixos-auto-deploy-key: ENC[AES256_GCM,data:YqyBDJnpJ9luLmFtKzvdJBqipi7qB2zCsuXLpFR0FKeCetnN3cXBD3+2YHNcMIFWmG/UVk7lO2JiP7IzeHADlik5FGd34eRkMNz8LiVUHR5ptyvkOHrqAAFSUFuTfKBhGzVp9RkrQ19ZXm3JzkZH8XckOYwjfJ5eoV0U3j0yJ53u/KXB3FnwN0J4zXr9mum6feYcs2dXel8+3sBSixvIZkaTKgIIWyHRwUlFNjKT0VLp8v0CETfYhLks+61Ya6S12u7yiyIvfMSW9kbhCBcZTrL39H9/1Fgkl+uHSkme5kf3V0cp79Ii1v5ivukBUAQMgQ2mmT1dj63fQ80aNbycxnCSuVck31mWrFnV4KT5OUb7bbYIt18Mo4PwAhhDG/r6UN5pCpDIGKgYJTKdx4Kn2Z8kfCegOkgPg4+6iUW1NVD90t1/pGpLGTjk1VWNfQjKGHyzbslPYqw7ZsrAUaF5H6Nu4QkwV1Mku1wGbE6/Qn/3t6PEpJeHQAjq6GMdY00/5pBf,iv:47UEQupDGKwWdNHR4yzGk7q4DCociU76e30Eb/1teOI=,tag:gZd/kcJpHLvWhU1t8KJh4g==,type:str]
loom-anthropic-api-key: ENC[AES256_GCM,data:9Rzb8T+f556cwLAY11hrk5jKWr6uYuDnWg==,iv:h9eOIoBNj2dmFfPx3O7Vz0JWo2bQYmHTUwYaGNEjs8Q=,tag:+KJLiaYd6mv1pZZCcFWcgA==,type:str]
loom-openai-api-key: ENC[AES256_GCM,data:lkPdGegps0qtrlIaraKnuPflP7oxiw==,iv:G3aFDYMnoO6fNb/+gudgRMfI7cZVBaHv1YIU67Ug7ho=,tag:OuqDf87x6jvkVKgiJR7zhg==,type:str]
loom-github-app-id: ENC[AES256_GCM,data:xWNFEfXb,iv:gnZ6AJkUD/QJotPNIa6e7YPlN08OplJA4TwT+yN0nkQ=,tag:z0M5LtLkvkiRGuA0srqbCQ==,type:str]
loom-github-app-private-key: ENC[AES256_GCM,data:phCk84Z0eKsnUkKbkvwT1AMIUOLEUoo=,iv:uiP9qcTwlx/VlyGeAO4rhS5GBJvAXGqtGAKN+mr9UUY=,tag:XNubFMl/vYpGLFi3UPkTig==,type:str]
loom-github-webhook-secret: ENC[AES256_GCM,data:jxXiq/N22ugBPpxNEvdScE5/V+9QQisiMsw=,iv:jQZH7dkOCz2d1SW3qM3DB6ib70QzQJ4lyIF2nSolx7k=,tag:VlNPncdLnjl6gkDAvvnjgg==,type:str]
loom-google-cse-api-key: ENC[AES256_GCM,data:AJ/n9RSUbOBs97yRp7Xk04eKs8R8fFcZDPUnu2tujHgdnw0sX/56,iv:UqTVaxGZaQVPen3/VdFSbqzs3yCiXQxog+TLWgtcTk4=,tag:j1DCXsy1czM5uy0laPbtHw==,type:str]
loom-google-cse-search-engine-id: ENC[AES256_GCM,data:8Ai1tjEf9fkUuusfp62DIQ0=,iv:lps0rYY4w974p7BnWosv8g2T+ff+4YAZEEIMrmswtSE=,tag:1Nq3rXgIXOr3CBD0efl7dw==,type:str]
sops:
    age:
        - recipient: age1sc7xejzhlq03wae7q4lte204a0lhz58y6p6skallk2204j8gcqpq6e67vq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhc2dKaHAvTWJha28ySFZt
            MkluaE1QTnhkWkhHS1JGb1NNN0pEaG1uWkdFCkRBWXVnRGF3cFpuNmI4bzBwKzFB
            QVdjNld2dGw3eUFyYk4zZmJnRkpuR1kKLS0tIGlqMWp4djdZdit5MGJLcEFJb20r
            VzJZcXFVQWZrT0h2NlNXTWlpS1BzeFkKKP20DqxJZ0/lhng06UQN2ZR86GF99TDj
            60jGL7IasASqPvk+pQdGkuU5C2PNAWxtLMsbHlIsD6GZRd4bmeBw7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z8g563muxm7pk02eqcfkrxlj8948yes3k8nj97t59jcygqavkpyqwj0zul
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdXBBaWo0RnJqSU84aUc1
            WGs5RGZIRExnTlkwRVpXNUVabmZhVGlubG5vClp6RnVPSUpGRkhyY0pGQmR2Z1BH
            c1Vnd2VyNG90MmRKSVkzWXhnTnpWeVEKLS0tIGoyYmNlLzBHNnd3SDRsclNXUngr
            S2w5UmhzK3NxVTNWTGY0bEJNNE5qU2MKddyjJ854CNIwmRzJlzVsgpKEeY5KngW9
            QEQJ64T0YQJgX7gNamckF8cN2zDqkzcqqQSkCoHhM34ng1njD0TB5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T15:51:14Z"
    mac: ENC[AES256_GCM,data:Ic+Ia1LqHTXP/o9Z/nb2mbuR00C09R2jIvXK32/72g/xPet4VpzarHLRTVfmzM9ip2VWdq0iJTzg4tzSlCCkWTyoNsTyrZuMwjXQ/N1ThPpUgEQa1Zqpg1oxAHntgc5/N+MWzWlNIcB++pmJsUf7pLgoUKiH/dvRhmlPhnIo864=,iv:pjThhKGmgiSxRv/yQLl71iO48K0aqniVuutE8ZVTvOE=,tag:t70eSOnTaDRqgk9iYtye3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
