#ENC[AES256_GCM,data:Aa+4P1ktTdIbju2p1h7krUnMF+0T,iv:zdvqgALheb0h9hyh6BDHaG4l6I4CkJX/8BpoWyoizsc=,tag:fjUYj8Lx8zprCg/R/Et5JQ==,type:comment]
#ENC[AES256_GCM,data:cgJrHkfiVGiA6Q6Y4fA1G806ENYK0IjVTxX6Gv5nhKKNrbamSWIjPRfXtjObB5M=,iv:O1uuXwPVaUfMW1nYJrIOl5YhLoDgjco6bNO1iXCjJeE=,tag:vjEQloA5Se5CcYoZBgCVjQ==,type:comment]
placeholder: ENC[AES256_GCM,data:jEU895Uq5/+J4A==,iv:xzOwvs0c8bPsIH9dFDdYiMf3hi2fcYM3FWuRL07hmtI=,tag:grTTvTyrlOMnwrp4LDQdbg==,type:str]
nixos-auto-deploy-key: ENC[AES256_GCM,data:SH+dl/JAlbUCoMXXj1xEbjUXDj1ZdcXBiHYWJnp3uiQg8YKAZ7U7wzsT2AoI7E4IwM3J9NcCQfLcCPPz13Vj8FqxiqSW1rWEHyxmOQv8tA/fWv25WHJic3U2AkS6HzSeZ+TOwKVEbwTnrXfAKdgby+MdBhdZB03ZO5hmCR2yNP5FPBe2DGqNJjo0ee9NrPSPk6yMTfxMgsJQDj6wV8GX54mcz9IXbyDenZ6W2DB07PFWnhHjA9+fEZSn27xS5Au+5xDqnBMDFVnHGtrfVmZy8BvFpnjObudK3ncsG3iSbdrZgZ74v3auXREod2+i78A1PYZt8fTiae+9heETUkmRU2Opiidlxe96RCe7YYAAFNKW8VjGvCNo2+CHGvdT3q6+F3jjmeFM68xS6OXci5GNfqZRjBQcPEa/QJkcDC4qLMZXzPb105FOz1H08ErCiZNkJh3pmTDjX6dHtdoT438CTpcfgcwgGKSSYPV9nlsJnb2OfsS1kB5Prk4txQPRlnO9LSht,iv:SlYDpPzMmcut6VrV5FL9Cidgc4vgPEb7GVVsGHavKvg=,tag:4gJsieAFEujLSudjM7Frtg==,type:str]
loom-anthropic-api-key: ENC[AES256_GCM,data:Lp7WONbEIktjJ3OSYfDLsIHLWNvHGtg+Ag==,iv:uf86oPXOeuGWbc4H1j3razQy02IdBut3QOJ9Dpkxg9Y=,tag:XaV532ibz5NSjVkE/I7T/w==,type:str]
loom-openai-api-key: ENC[AES256_GCM,data:7RJMmHbN1ii1PVb4Ik+54gR+klSL2A==,iv:HlU5yczkBqoMosC4cCNITdqHyJWFogv4wp/kRN4VC5g=,tag:soLz/CTapjHPvUp0fhv2VA==,type:str]
loom-github-app-id: ENC[AES256_GCM,data:+tR7aUkr,iv:Gf5heW+LGi9sRT1iVjDT6g7C40V5lZuonp/0/tLFxzk=,tag:O/UQ89x1Phtn0DA2VGz0XQ==,type:str]
loom-github-app-private-key: ENC[AES256_GCM,data:MgeriwPCZ7o3xISymjS++V8I1RxKpE4=,iv:YiAZFgBztvqGdTSGZiFLWLLmVM32G9PNG/JLWz5Eozs=,tag:1hAXZaCfv81znWQZ3QblNA==,type:str]
loom-github-webhook-secret: ENC[AES256_GCM,data:LeYiQplr3yULatv6lQSlqtY5saaN/zDsyDw=,iv:7q2ENmV5gbqzVLEOARuDAD/9In21RRwJq1eLPw1kcyQ=,tag:Imc/qSZkqd7l8ph0pxu4iA==,type:str]
loom-google-cse-api-key: ENC[AES256_GCM,data:qdKytPYe9Zk7bSXJSLFUyl2waCNqeXSOwug3o4VsrAzx5ZAi7DBl,iv:7yAaobnxbIra/4lMuW8mzTYwLBzaUcl8T4vaWj5OcTg=,tag:SAVcoE3OVIXDImMrri6fig==,type:str]
loom-google-cse-search-engine-id: ENC[AES256_GCM,data:sWsq3rrU0Kt/J/9yBnGcKSo=,iv:LCVtPNdSustfCkpb0FEPVOwz7NGz2OdFzSliskIClaI=,tag:9wrcuMRVc6jHQXVg8p1yqw==,type:str]
sops:
    age:
        - recipient: age1sc7xejzhlq03wae7q4lte204a0lhz58y6p6skallk2204j8gcqpq6e67vq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeG51SW5DM3VEOStpWjI4
            Y0ppTHlGYU1Gc280MWxuaHlQcXV6eFFKQUJJCk1VRExvWUlBZXJBY3gwOXNJN0Jl
            cGJpam9UUFE4TGgxR1JWaFRGbTBzYUEKLS0tIEZ6aUY1MVFrc1ZQbFdYNkVKMXFW
            WFBZU0lxYWtmSFlPUmQwUUtLRk1TbkEKQSbmjWQHx4gO6J0oKt5DHi/fsKEYhYW/
            6uequwz8iwx1rGQrag9UebWyDdsUdXqYFV8ulZlPZdvpo/Q9g3SEWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z8g563muxm7pk02eqcfkrxlj8948yes3k8nj97t59jcygqavkpyqwj0zul
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZDBuZW1RTGVUdWdOc2hL
            MkE4cEZ2S3pOQk9zQ0xCd1FUNllmbE9hTzIwCkZLdDYra1FwTlQxNGpuWFZLZkM0
            REpyaVdRWHQrZmJnZkVyTmpqYXVVeEkKLS0tIHAyT2xtMzZTWTcya1RFTVZ6U3JI
            Z3RrazZXM0FURUY1WUhCNVhONlNUN1UK5E5/m6m1CNIdII+YPvZ5SWd0CFPlj2C3
            LRhtmaw/edX4AuKJCSa3pKxkIu7Fu3E7Ziw38ssuwAZiNFZ8i5pb3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T06:36:56Z"
    mac: ENC[AES256_GCM,data:tgBw5NOG6SLiMSg5wR+lS4nhXDrCK1boSPRmdqHguqlQJqhSjfFK2myHEZqILYnFDzJzz33JS1pcs0WrwM4GExbPZ0N8tWb+10owG3pWnuCLVBBasRzpGPqAt9eyX+cCFgHItRYuzZqJj3sN3AAyEHTTMPqy9by29tpy0xYGDa4=,iv:9P1XVwYBSt6SOZDH7VedD9/Z53Jhok+TnhtbA0KhAbE=,tag:xfKviEzKHLILcOPG/Kd1mQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
